language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt
- pip install python-coveralls
env:
- SETTINGS='config.TestConfig'
script:
- pwd
- /home/travis/build/LandRegistry/matching/db/create-database.sh
- APP_ROOT=/home/travis/build/LandRegistry/matching /home/travis/build/LandRegistry/matching/db/upgrade-database.sh
- source ./environment_test.sh
- py.test --cov matching tests/ --cov-report=term --cov-report=html
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: BvMjyroywBp8Pv/cgj1TNmmaAJNFlQCiHOUcddaO06YPIpVN7IwvU9e4YbBUVjLQdhyXl+OhZdV/Pm3CtPD6IDpCcQN7hPrBrpP2s6hLNxIVEMSwIv0sRdcM04jDm8S7Uy+B1jvGTmpHZdyW/kPlP4VFVNnVDThg837tRSQ8zkQ=
  app: lr-matching
  on:
    repo: LandRegistry/matching
  run: "python manage.py db upgrade"

