language: python
python:
- '2.7'
addons:
  postgresql: '9.3'
install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt
- pip install python-coveralls
env:
- SETTINGS='config.TestConfig'
script:
- source ./environment_test.sh
- "/home/travis/build/LandRegistry/matching/db/create_database.sh"
- py.test --cov matching tests/ --cov-report=term --cov-report=html
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: nfpWUxjf7mqy2E5GQX65ruHFgdMhXlgkUVRQkzuNWMgn0h6ehZ6y7q1sM88Lacq8zqYuC59ggRT5470F4T3hiTv88yMvORvkFmE476DeutOxABZIkCmHIWE+YlTHhF/YYjV3jVopkO2hsqZhaDcIX4mwUR7NHwd+w/1oHr+P/lg=
  app: lr-matching
  on:
    repo: LandRegistry/matching
