language: python
python:
- '2.7'
addons:
  postgresql: '9.3'
install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt
- pip install python-coveralls
env:
- SETTINGS='config.TestConfig'
script:
- source ./environment_test.sh
- "/home/travis/build/LandRegistry/matching/db/create_database.sh"
- py.test --cov matching tests/ --cov-report=term --cov-report=html
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: ZRUvKiCNDawAycOB+6WVs0DHzW4vRWneS7b+XQMQAVYSjW6tPvOGvlgu3ldF/SwMuF3gRoFutFFL/wnoY/fLH7lI3BJyb6rYPkTR5MWIFLOS859+CphZWqB5bI4FWDiXSIxBimxXuUADmRUIiybIMD5Z68Gxaedeq09eE+IZ55E=
  app: lr-matching
  on:
    repo: LandRegistry/matching
