language: python
python:
- '2.7'
addons:
  postgresql: '9.3'
install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt
- pip install python-coveralls
env:
- SETTINGS='config.TestConfig'
script:
- source ./environment_test.sh
- /home/travis/build/LandRegistry/matching/db/create_database.sh
- py.test --cov matching tests/ --cov-report=term --cov-report=html
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: B0JvdAfkWzYwPQ7Z+ZObTFXaJgOIZMxaworQrXV8qVfuG6ZHsC35VZk1WOqB7CD8ZErsqgaRBNkQQsaagZAeJ3GKcrBwjohSkNMQnsAjXYci+LbDTM//YlDPNnwbmq/t/mxG6IM1BK2Hph6u1xTXZvTCxMdPQKnl7/jMWFeRabg=
  app: lr-matching
  on:
    repo: LandRegistry/matching
  run: python manage.py db upgrade
