"""empty message

Revision ID: 3cc4dd8d9508
Revises: de99eeaf0c3
Create Date: 2014-10-22 11:44:41.324057

"""

# revision identifiers, used by Alembic.
revision = '3cc4dd8d9508'
down_revision = 'de99eeaf0c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blocked')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('blocked', sa.BOOLEAN(), server_default='false', autoincrement=False, nullable=False))
    ### end Alembic commands ###
