"""empty message

Revision ID: 541b18fcaa9b
Revises: None
Create Date: 2014-08-28 14:15:38.376780

"""

# revision identifiers, used by Alembic.
revision = '541b18fcaa9b'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('F', 'M', name='gender_types'), nullable=False),
    sa.Column('current_address', sa.TEXT(), nullable=False),
    sa.Column('previous_address', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
